name: Release
on: 
  push: 
    branches: 
      - main
  workflow_dispatch:
env: 
  VERSION: '14.0.0'  # Updated version number to 14.0.0
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Remove unwanted files
        run: |
          rm -rf my_workspaces/.my_workspaces
          rm -rf README.md
          rm -rf README_EN.md
          rm -rf .git
          rm -rf .github
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with: 
          tag_name: ${{ env.VERSION }}
          release_name: UY-Scuti ${{ env.VERSION }}
          draft: false
          prerelease: false
          body: |
            ## 更新内容

            1. **F2FS 分区打包优化**: 回归到更合理的动态大小计算方式（目录大小的 1.05 倍 + 55MB 额外空间），以避免因空间不足导致的打包失败。
            2. **EXT4 分区解包**: 移除了对 `debugfs` 的依赖，转而使用纯 Python 实现，现在解包不再需要 ROOT 权限。

            ## Release Notes

            1. **F2FS Partition Packaging Optimization**: Reverted to a more reasonable dynamic size calculation method (1.05 times the directory size + 55MB extra space) to avoid packaging failures due to insufficient space.
            2. **EXT4 Partition Unpacking**: Removed the dependency on `debugfs` and switched to a pure Python implementation. Unpacking no longer requires ROOT permissions.

      - name: Archive project
        run: zip -r UY-Sct_${{ env.VERSION }}.zip .
        
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
        with: 
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./UY-Sct_${{ env.VERSION }}.zip
          asset_name: UY-Sct_${{ env.VERSION }}.zip
          asset_content_type: application/zip
